DROP TABLE Users CASCADE CONSTRAINTS; 
DROP TABLE Carrer CASCADE CONSTRAINTS;
DROP TABLE Users_Carrer CASCADE CONSTRAINTS;
DROP TABLE Subject CASCADE CONSTRAINTS;
DROP TABLE Subject_Carrer CASCADE CONSTRAINTS;
DROP TABLE Teacher CASCADE CONSTRAINTS;
DROP TABLE Teacher_Subject CASCADE CONSTRAINTS;
DROP TABLE Evaluations CASCADE CONSTRAINTS;




CREATE TABLE Users
(
	id_user              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	first_name           VARCHAR(20)  NULL ,
	last_name            VARCHAR(20)  NULL ,
	email                VARCHAR(30)  NULL ,
	password             VARCHAR(20)  NULL ,
CONSTRAINT  XPKUsers PRIMARY KEY (id_user)
);

CREATE TABLE Carrer
(
	id_carrer            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	name_carrer          VARCHAR(20)  NULL ,
CONSTRAINT  XPKCarrer PRIMARY KEY (id_carrer)
);

CREATE TABLE Users_Carrer
(
	id_user              INT  NOT NULL ,
	id_carrer            INT  NOT NULL ,
CONSTRAINT  XPKUsers_Carrer PRIMARY KEY (id_user,id_carrer),

CONSTRAINT R_9 FOREIGN KEY (id_user) REFERENCES Users (id_user),

CONSTRAINT R_10 FOREIGN KEY (id_carrer) REFERENCES Carrer (id_carrer)
);

CREATE TABLE Subject
(
	id_subject           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	name_subject         VARCHAR(50)  NULL ,
CONSTRAINT  XPKSubject PRIMARY KEY (id_subject)
);

CREATE TABLE Subject_Carrer
(
	id_subject           INT  NOT NULL ,
	id_carrer            INT  NOT NULL ,
CONSTRAINT  XPKSubject_Carrer PRIMARY KEY (id_subject,id_carrer),

CONSTRAINT R_5 FOREIGN KEY (id_subject) REFERENCES Subject (id_subject),

CONSTRAINT R_6 FOREIGN KEY (id_carrer) REFERENCES Carrer (id_carrer)
);

CREATE TABLE Teacher
(
	id_teacher           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	firrst_name          VARCHAR(20)  NULL ,
	last_name            VARCHAR(20)  NULL ,
	score_teacher        DEC(3,2)  NULL ,
CONSTRAINT  XPKTeacher PRIMARY KEY (id_teacher)
);

CREATE TABLE Theacher_Subject
(
	id_teacher           INT  NOT NULL ,
	id_subject           INT  NOT NULL ,
CONSTRAINT  XPKTheacher_Subject PRIMARY KEY (id_teacher,id_subject),

CONSTRAINT R_2 FOREIGN KEY (id_teacher) REFERENCES Teacher (id_teacher),

CONSTRAINT R_3 FOREIGN KEY (id_subject) REFERENCES Subject (id_subject)
);

CREATE TABLE Evaluations
(
	id_evaluation        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	id_teacher           INT  NULL ,
CONSTRAINT  XPKEvaluations PRIMARY KEY (id_evaluation),

CONSTRAINT R_7 FOREIGN KEY (id_teacher) REFERENCES Teacher (id_teacher)
);
